project_id = "lvderlqrkhodaelknydl"

[auth]
site_url = "https://gwlanguageflow.com.br"
additional_redirect_urls = [
  "https://gwlanguageflow.com.br/**",
  "https://www.gwlanguageflow.com.br/**",
  "https://flow-lingua-hub-gwlanguageflow-uxs-projects.vercel.app/**",
  "https://flow-lingua-hub-git-main-gwlanguageflow-uxs-projects.vercel.app/**",
  "http://localhost:3000/**",
  "http://localhost:4177/**",
  "http://localhost:8080/**",
  "http://127.0.0.1:4177/**"
]

[auth.email]
enable_confirmations = false
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
