project_id = "lvderlqrkhodaelknydl"

[auth]
site_url = "https://gwlanguageflow.com.br"
additional_redirect_urls = [
  "https://gwlanguageflow.com.br/**",
  "https://www.gwlanguageflow.com.br/**"
]

[auth.email]
enable_confirmations = false
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
