declare module "lucide-react" {
  import * as React from "react";

  export type LucideProps = React.SVGProps<SVGSVGElement> & {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  };

  export type LucideIcon = React.ForwardRefExoticComponent<
    LucideProps & React.RefAttributes<SVGSVGElement>
  >;

  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Archive: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const BadgeCheck: LucideIcon;
  export const Banknote: LucideIcon;
  export const BarChart3: LucideIcon;
  export const BellRing: LucideIcon;
  export const BookOpen: LucideIcon;
  export const BookOpenCheck: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarCheck: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronLeftIcon: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Circle: LucideIcon;
  export const ClipboardCheck: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Clock: LucideIcon;
  export const Cookie: LucideIcon;
  export const Copy: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const FileText: LucideIcon;
  export const Filter: LucideIcon;
  export const Flame: LucideIcon;
  export const FolderOpen: LucideIcon;
  export const Globe2: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Headphones: LucideIcon;
  export const HeartHandshake: LucideIcon;
  export const History: LucideIcon;
  export const ImagePlus: LucideIcon;
  export const Languages: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const LineChart: LucideIcon;
  export const Link: LucideIcon;
  export const Loader2: LucideIcon;
  export const LockKeyhole: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Megaphone: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessagesSquare: LucideIcon;
  export const Minus: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const PencilLine: LucideIcon;
  export const Plus: LucideIcon;
  export const QrCode: LucideIcon;
  export const RefreshCcw: LucideIcon;
  export const Scale: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings2: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Star: LucideIcon;
  export const Target: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Trophy: LucideIcon;
  export const Upload: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const UserPlus: LucideIcon;
  export const UserRound: LucideIcon;
  export const UserRoundCheck: LucideIcon;
  export const UserX: LucideIcon;
  export const Users: LucideIcon;
  export const Video: LucideIcon;
  export const Wallet: LucideIcon;
  export const WalletCards: LucideIcon;
  export const X: LucideIcon;
}
